apiVersion: v1
kind: ReplicationController
metadata: 
  name: motorboat
spec:
  replicas: 1
  selector:
    name: motorboat 
  template:
    metadata:
      labels:
         name: motorboat
    spec:
      containers: 
        - name: "motorboat"
          image: "b.gcr.io/kuar/motorboat:0.0.1"
          args: 
            - "--api-server=10.240.178.167:8080"
            - "--nginx-server=10.240.26.48:8080"
            - "--nginx-status-server=10.240.26.48:9090"
